worker_processes  1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    # Servidor para la app React portable
    server {
        listen       8080;
        server_name  localhost;

        # Ruta absoluta al build estático
        root   ../build;
        index  index.html;

        # Para que React Router funcione correctamente
        location / {
            try_files $uri /index.html;
        }
    }
}
